# -*- coding: utf-8 -*-
"""SwapFace.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/victorgeel/FaceSwapNoNfsw/blob/main/SwapFace.ipynb
"""

!git lfs install
!git clone https://huggingface.co/spaces/victorisgeek/DeepSwapFace

# Commented out IPython magic to ensure Python compatibility.
#@title
# %cd /content/DeepSwapFace
print("Installing requirements...")
!pip install -r requirements.txt -q
!pip install gdown
print("Installing requirements done.")

default_output_path = "/content/DeepSwapFace" #@param {type:"string"}

command = f"python app.py --cuda --colab --out_dir {default_output_path}"
!{command}